# Generated by Django 4.2 on 2023-05-03 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaturemodel',
            name='check_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adr.adrcheck'),
        ),
    ]
