# Generated by Django 4.2 on 2023-05-03 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adr', '0002_signaturemodel_check_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signaturemodel',
            name='user',
        ),
    ]
