# Generated by Django 4.2 on 2023-05-03 16:41

from django.db import migrations
import jsignature.fields


class Migration(migrations.Migration):

    dependencies = [
        ('adr', '0003_remove_signaturemodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='adrcheck',
            name='signature',
            field=jsignature.fields.JSignatureField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='SignatureModel',
        ),
    ]
