# Generated by Django 4.2 on 2023-05-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adr', '0004_adrcheck_signature_delete_signaturemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adrcheck',
            name='field1',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], default='1', max_length=1),
        ),
    ]
