# Generated by Django 4.2 on 2023-05-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adr', '0005_alter_adrcheck_field1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adrcheck',
            name='field1',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='adrcheck',
            name='truck_origin',
            field=models.CharField(choices=[('A', 'A-Österrich'), ('HR', 'HR-Kroatien'), ('SK', 'SK-Slowakei'), ('D', 'D-Deutschland'), ('RO', 'RO-Rumänien'), ('PL', 'PL-Polen'), ('BG', 'BG-Bulgarien'), ('CZ', 'CZ-Tschechien'), ('H', 'H-Ungarn'), ('GR', 'EL/GR-Griechenland'), ('I', 'I-Italen'), ('DK', 'DK-Dänemark'), ('EST', 'EST-Estland'), ('FIN', 'Finnland'), ('F', 'F-Frankreich'), ('IRL', 'IRL-Irland'), ('LV', 'LV-Lettland'), ('LT', 'LT-Litauen'), ('L', 'L-Luxemburg'), ('M', 'M-Malta'), ('NL', 'NL-Niederlande'), ('P', 'P-Portugal'), ('S', 'S-schweden'), ('E', 'E-Spanien'), ('CY', 'CY-Zypern')], max_length=20),
        ),
    ]
