# Generated by Django 4.2 on 2023-05-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adr', '0008_alter_adrcheck_truck_art_alter_adrcheck_truck_origin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adrcheck',
            name='field1',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2')], default='1', max_length=1, null=True),
        ),
    ]
