# Generated by Django 4.2 on 2023-05-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adr', '0010_adrcheck_check_40_adrcheck_check_41_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adrcheck',
            name='truck_art',
            field=models.CharField(blank=True, choices=[('Planne', 'Planne'), ('Aufbau ohne Kühler', 'Aufbau ohne Kühler'), ('Aufbau mit Kühler', 'Aufbau mit Kühler')], max_length=18),
        ),
        migrations.AlterField(
            model_name='adrcheck',
            name='truck_origin',
            field=models.CharField(blank=True, choices=[('Österreich', 'A-Österreich'), ('Kroatien', 'HR-Kroatien'), ('Slowakei', 'SK-Slowakei'), ('Deutschland', 'D-Deutschland'), ('Rumänien', 'RO-Rumänien'), ('Polen', 'PL-Polen'), ('Bulgarien', 'BG-Bulgarien'), ('Tschechien', 'CZ-Tschechien'), ('Ungarn', 'H-Ungarn'), ('Griechenland', 'EL/GR-Griechenland'), ('Italen', 'I-Italen'), ('Dänemark', 'DK-Dänemark'), ('Estland', 'EST-Estland'), ('Finnland', 'Finnland'), ('Frankreich', 'F-Frankreich'), ('Irland', 'IRL-Irland'), ('Lettland', 'LV-Lettland'), ('Litauen', 'LT-Litauen'), ('Luxemburg', 'L-Luxemburg'), ('Malta', 'M-Malta'), ('Niederlande', 'NL-Niederlande'), ('Portugal', 'P-Portugal'), ('Schweden', 'S-Schweden'), ('Spanien', 'E-Spanien'), ('Zypern', 'CY-Zypern')], max_length=20),
        ),
        migrations.AlterField(
            model_name='adrcheck',
            name='type',
            field=models.CharField(blank=True, choices=[('Sattelzug', 'Sattelzug'), ('Motorwagen', 'Motorwagen')], max_length=20),
        ),
    ]
