# Generated by Django 4.2 on 2023-05-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adr', '0011_alter_adrcheck_truck_art_alter_adrcheck_truck_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adrcheck',
            name='field3',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
